CURRENT_DIR=`pwd`
export ARDEFACT_WEB=$CURRENT_DIR/ardefact_web
export ARDEFACT_API=$CURRENT_DIR/ardefact_api
export BUILD_DIR=$CURRENT_DIR/build
export PP=$CURRENT_DIR/makefileEcho.sh
export A_STATIC_ROOT=$ARDEFACT_WEB/ardefact-web
export A_EXEC_BUNYAN=$A_EXEC_BUNYAN
export A_STATIC_BUILD_CONTENT_ROOT=$BUILD_DIR/static
export A_EXEC_PREPROCESS_STATIC=$ARDEFACT_API/ardefact-api/preProcessStaticContent.js
export A_EXEC_NPM=$A_EXEC_NPM
export A_EXEC_NODE=$A_EXEC_NODE
export A_EXEC_JSHINT=$A_EXEC_JSHINT
export A_EXEC_BOWER=$ARDEFACT_API/ardefact-api/node_modules/bower/bin/bower
export A_EXEC_STATIC_CONTENT_SERVER=$ARDEFACT_API/ardefact-api/StaticContentServer.js
